container:
  image: node:latest

env:
  NG_CLI_ANALYTICS: false
  CHROME_BIN: chromium-browser

test_task:
  node_modules_cache:
    folder: node_modules
    populate_script: yarn install
  lib_test_script: yarn run ci.travis.lib
  demo_test_script: yarn run ci.travis.demo
